### PR TITLE
Feature add bower js library

### PR DESCRIPTION
**Pull request by varffs**
no long use /ls/library/*

### CODE REVIEW

**Comment by mixcas** [comment]
@varffs what about modules that are not on bower but on npm?

**Comment by varffs** [comment]
like what? this is for js frontend lib stuff where everything is gonna be in bower

**Comment by mixcas** [comment]
I don't have an example right now but I think it has happened to me before. NPM is not exclusevly for node nor backend.

**Comment by mixcas** [comment]
What if the module is not on either?

**Comment by varffs** [comment]
then thats a ballache that we have to solve at the time. but as you can install from git repos I'm sure its ok https://bower.io/docs/api/#install

**Comment by varffs** [comment]
even just urls

**Comment by varffs** [comment]
rtfm etc etc

**Comment by mixcas** [comment]
Oh cool

What are the steps to do this? should it be in the README?

**Comment by varffs** [comment]
ah yh def. I'll add that

**Comment by mixcas** [comment]
@varffs check changes and merge

**Pull request merged**
