### PR TITLE
fix duplicate Site Options menus

### PR DESCRIPTION
**Pull request by mixcas**

### CODE REVIEW

**Comment by varffs** [comment]
Does this remove as much surplus code as possible? 

I think this fix needs to also refactor the way we do theme options (we no longer need a folder just for them and don't think we need any of the previously included class?) It also should update the declaration of metaboxes to using the newer style (that we use for normal metaboxes now)

**Comment by mixcas** [comment]
Yeah that should be done in other PRs because this one specifically fixes only that little issue.

**Comment by varffs** [comment]
I think this is bad practice to just patch the codebase for a quick fix on our starter pack.

**Comment by mixcas** [comment]
I agree 100% with your proposal to improve the whole declaration of Site Options.

But I don't think this is a hotfix. The issue was a double declaration for the menu link. Once in our code, once in the new CMB2 code. This solves it in a reasonable way, non hacky or anyway sketchy.

The rest of our code for Site Options still is valid code and still works fine. I don't see why this PR should forced to expand it's scope. I think there's not a minimum change size for a PR and I believe in always using as many commits and PRs are needed instead of fewer.

I suggest merging this, opening an improvement issue and doing the refactor on it's own branch.

**Comment by varffs** [comment]
I was going to close and do my own branch. But just wanted it nice sooner rather than later. So over to you

**Pull request merged**
